# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/kuehnmarissa"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/kuehnmarissa/"

[social.params]
icon = ""

[[social]]
identifier = "kaggle"
name = "Kaggle"
url = "https://www.kaggle.com/marissakuehn"

[social.params]
icon = ""